### ISSUE TITLE
Not really an issue, but a feature request?

### ISSUE THREAD

**Issue by Duckman33** [UbhiTS/ad-alexasmarttalkingthermostat#1]
I'm wondering if it's possible to add into this some geofencing functionality to have the HVAC system turn off when everyone (or the last person) in the house leaves, and turn back on again when anyone arrives?

I am currently doing something very close to this in WebCoRE minus the Alexa talking part, but I'm really trying to migrate away from Smartthings completely, as I'm having way too many isues with it working reliably. However, I dont have a mini-split system and I don't have the ability to control the climate in each room seperately. We have a heat pump/furnace installation that is all or nothing pretty much. That said, turing the system off at a certain time unfortunatly won't work for my setup, since we dont come and go at any specific time of the day or night. 

I'd attempt to add it myself but I'm new to HASSIO and don't really understand the coding part of it quite yet, or if you don't want to add this into the main app.yaml file, maybe you could point me in the right direction on what I'd need to do in order to add that functionality into the apps.yaml on my end?

I appologize if this is the wrong place to make a request like this, I couldn't see any other way to do it.

**Comment by UbhiTS** [comment]
hi Duckman33. let me think about it to see if and how I can integrate or let you know a workaround. Give me a couple of days. Thanks

**Comment by UbhiTS** [comment]
Could we have a quick call so I can understand your setup and use case in detail. And yes, I was a SmartThings user myself for more than a year. Was very happy, until these guys force migrated my app and I lost all data and they simply said "Sorry, you'll need to setup your network again." ... that was the day, and today, I've never had an issue with HassIO. I can promise you'll definitely be happier.

**Comment by Duckman33** [comment]
Hi Tarunpreet,

First, thanks for getting back to me. Sorry it took a while to get back to you, I can do one better. I will attach my Webcore piston and you can see what It was doing.

Yeah, I'm already happier about moving to HA and I have only done one flow in Node Red so far but at least it works and I don't have to wait 30 seconds to a minute+ for it to work, LOL

Please see the attached Webcore Piston, the code is in the screenshot, but you probably aren't using Webcore.[cid:0b83af35-2b3a-4338-9075-85c7fac829c6]
________________________________

**Comment by UbhiTS** [comment]
I was a fan of webcore too before HA. I'm sorry, I'm unable to see the Piston, where's the attachment ?

**Comment by Duckman33** [comment]
I'll try again, maybe hotmail thought it was too big. It's just a pic of the piston[cid:6ead49db-281b-42cd-a04c-13ff20104604] with the backup code
________________________________

**Comment by Duckman33** [comment]
OK I'm an idiot. I was replying from Hotmail instead of in this thread. Let me try attaching the piston again but in here instead. Sorry about that. 
![HVAC control](https://user-images.githubusercontent.com/5788582/93832447-a4af4f80-fc2a-11ea-8a84-649b7d7f4158.png)

**Comment by UbhiTS** [comment]
hi, after a year of a break almost, I'm back. are you still using this integration? do you want this fixed ?

**Comment by Duckman33** [comment]
Hello,

I moved on to a ecobee thermostat and it does everything I need so I'm good. But thanks for getting back to me!

-
Ted.
________________________________

**Comment by UbhiTS** [comment]
thank you :)
